/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmOrderRouteImport } from './routes/confirm-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportDefectiveRouteImport } from './routes/report-defective'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountPaymentMethodsRouteImport } from './routes/account.payment-methods'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountVouchersRouteImport } from './routes/account.vouchers'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivityLogsRouteImport } from './routes/_authenticated/admin.activity-logs'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminDefectReportsRouteImport } from './routes/_authenticated/admin.defect-reports'
import { Route as AuthenticatedAdminDiagnosticRouteImport } from './routes/_authenticated/admin.diagnostic'
import { Route as AuthenticatedAdminHhcRouteImport } from './routes/_authenticated/admin.hhc'
import { Route as AuthenticatedAdminLowStockRouteImport } from './routes/_authenticated/admin.low-stock'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminProductHuntingRouteImport } from './routes/_authenticated/admin.product-hunting'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminUserDataRouteImport } from './routes/_authenticated/admin.user-data'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminVouchersRouteImport } from './routes/_authenticated/admin.vouchers'
import { Route as AuthenticatedAdminWebsiteReviewsRouteImport } from './routes/_authenticated/admin.website-reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmOrderRoute = ConfirmOrderRouteImport.update({
  id: '/confirm-order',
  path: '/confirm-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDefectiveRoute = ReportDefectiveRouteImport.update({
  id: '/report-defective',
  path: '/report-defective',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentMethodsRoute = AccountPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVouchersRoute = AccountVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityLogsRoute =
  AuthenticatedAdminActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDefectReportsRoute =
  AuthenticatedAdminDefectReportsRouteImport.update({
    id: '/defect-reports',
    path: '/defect-reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticRoute =
  AuthenticatedAdminDiagnosticRouteImport.update({
    id: '/diagnostic',
    path: '/diagnostic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHhcRoute = AuthenticatedAdminHhcRouteImport.update({
  id: '/hhc',
  path: '/hhc',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLowStockRoute =
  AuthenticatedAdminLowStockRouteImport.update({
    id: '/low-stock',
    path: '/low-stock',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductHuntingRoute =
  AuthenticatedAdminProductHuntingRouteImport.update({
    id: '/product-hunting',
    path: '/product-hunting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUserDataRoute =
  AuthenticatedAdminUserDataRouteImport.update({
    id: '/user-data',
    path: '/user-data',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVouchersRoute =
  AuthenticatedAdminVouchersRouteImport.update({
    id: '/vouchers',
    path: '/vouchers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteReviewsRoute =
  AuthenticatedAdminWebsiteReviewsRouteImport.update({
    id: '/website-reviews',
    path: '/website-reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-order': typeof ConfirmOrderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/register': typeof RegisterRoute
  '/report-defective': typeof ReportDefectiveRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/defect-reports': typeof AuthenticatedAdminDefectReportsRoute
  '/admin/diagnostic': typeof AuthenticatedAdminDiagnosticRoute
  '/admin/hhc': typeof AuthenticatedAdminHhcRoute
  '/admin/low-stock': typeof AuthenticatedAdminLowStockRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/product-hunting': typeof AuthenticatedAdminProductHuntingRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/user-data': typeof AuthenticatedAdminUserDataRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vouchers': typeof AuthenticatedAdminVouchersRoute
  '/admin/website-reviews': typeof AuthenticatedAdminWebsiteReviewsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-order': typeof ConfirmOrderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/report-defective': typeof ReportDefectiveRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
  '/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/defect-reports': typeof AuthenticatedAdminDefectReportsRoute
  '/admin/diagnostic': typeof AuthenticatedAdminDiagnosticRoute
  '/admin/hhc': typeof AuthenticatedAdminHhcRoute
  '/admin/low-stock': typeof AuthenticatedAdminLowStockRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/product-hunting': typeof AuthenticatedAdminProductHuntingRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/user-data': typeof AuthenticatedAdminUserDataRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vouchers': typeof AuthenticatedAdminVouchersRoute
  '/admin/website-reviews': typeof AuthenticatedAdminWebsiteReviewsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-order': typeof ConfirmOrderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/register': typeof RegisterRoute
  '/report-defective': typeof ReportDefectiveRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/defect-reports': typeof AuthenticatedAdminDefectReportsRoute
  '/_authenticated/admin/diagnostic': typeof AuthenticatedAdminDiagnosticRoute
  '/_authenticated/admin/hhc': typeof AuthenticatedAdminHhcRoute
  '/_authenticated/admin/low-stock': typeof AuthenticatedAdminLowStockRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/product-hunting': typeof AuthenticatedAdminProductHuntingRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/user-data': typeof AuthenticatedAdminUserDataRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vouchers': typeof AuthenticatedAdminVouchersRoute
  '/_authenticated/admin/website-reviews': typeof AuthenticatedAdminWebsiteReviewsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/confirm-order'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/products'
    | '/register'
    | '/report-defective'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/account/addresses'
    | '/account/orders'
    | '/account/payment-methods'
    | '/account/reviews'
    | '/account/vouchers'
    | '/account/wishlist'
    | '/category/$slug'
    | '/products/$productId'
    | '/products/'
    | '/admin/activity-logs'
    | '/admin/ai'
    | '/admin/defect-reports'
    | '/admin/diagnostic'
    | '/admin/hhc'
    | '/admin/low-stock'
    | '/admin/orders'
    | '/admin/product-hunting'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/user-data'
    | '/admin/users'
    | '/admin/vouchers'
    | '/admin/website-reviews'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/confirm-order'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/register'
    | '/report-defective'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/account/addresses'
    | '/account/orders'
    | '/account/payment-methods'
    | '/account/reviews'
    | '/account/vouchers'
    | '/account/wishlist'
    | '/category/$slug'
    | '/products/$productId'
    | '/products'
    | '/admin/activity-logs'
    | '/admin/ai'
    | '/admin/defect-reports'
    | '/admin/diagnostic'
    | '/admin/hhc'
    | '/admin/low-stock'
    | '/admin/orders'
    | '/admin/product-hunting'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/user-data'
    | '/admin/users'
    | '/admin/vouchers'
    | '/admin/website-reviews'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/confirm-order'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/products'
    | '/register'
    | '/report-defective'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/account/addresses'
    | '/account/orders'
    | '/account/payment-methods'
    | '/account/reviews'
    | '/account/vouchers'
    | '/account/wishlist'
    | '/category/$slug'
    | '/products/$productId'
    | '/products/'
    | '/_authenticated/admin/activity-logs'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/defect-reports'
    | '/_authenticated/admin/diagnostic'
    | '/_authenticated/admin/hhc'
    | '/_authenticated/admin/low-stock'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/product-hunting'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/user-data'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vouchers'
    | '/_authenticated/admin/website-reviews'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmOrderRoute: typeof ConfirmOrderRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportDefectiveRoute: typeof ReportDefectiveRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-order': {
      id: '/confirm-order'
      path: '/confirm-order'
      fullPath: '/confirm-order'
      preLoaderRoute: typeof ConfirmOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-defective': {
      id: '/report-defective'
      path: '/report-defective'
      fullPath: '/report-defective'
      preLoaderRoute: typeof ReportDefectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payment-methods': {
      id: '/account/payment-methods'
      path: '/payment-methods'
      fullPath: '/account/payment-methods'
      preLoaderRoute: typeof AccountPaymentMethodsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/vouchers': {
      id: '/account/vouchers'
      path: '/vouchers'
      fullPath: '/account/vouchers'
      preLoaderRoute: typeof AccountVouchersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity-logs': {
      id: '/_authenticated/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/defect-reports': {
      id: '/_authenticated/admin/defect-reports'
      path: '/defect-reports'
      fullPath: '/admin/defect-reports'
      preLoaderRoute: typeof AuthenticatedAdminDefectReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostic': {
      id: '/_authenticated/admin/diagnostic'
      path: '/diagnostic'
      fullPath: '/admin/diagnostic'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hhc': {
      id: '/_authenticated/admin/hhc'
      path: '/hhc'
      fullPath: '/admin/hhc'
      preLoaderRoute: typeof AuthenticatedAdminHhcRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/low-stock': {
      id: '/_authenticated/admin/low-stock'
      path: '/low-stock'
      fullPath: '/admin/low-stock'
      preLoaderRoute: typeof AuthenticatedAdminLowStockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/product-hunting': {
      id: '/_authenticated/admin/product-hunting'
      path: '/product-hunting'
      fullPath: '/admin/product-hunting'
      preLoaderRoute: typeof AuthenticatedAdminProductHuntingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/user-data': {
      id: '/_authenticated/admin/user-data'
      path: '/user-data'
      fullPath: '/admin/user-data'
      preLoaderRoute: typeof AuthenticatedAdminUserDataRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vouchers': {
      id: '/_authenticated/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AuthenticatedAdminVouchersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website-reviews': {
      id: '/_authenticated/admin/website-reviews'
      path: '/website-reviews'
      fullPath: '/admin/website-reviews'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityLogsRoute: typeof AuthenticatedAdminActivityLogsRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminDefectReportsRoute: typeof AuthenticatedAdminDefectReportsRoute
  AuthenticatedAdminDiagnosticRoute: typeof AuthenticatedAdminDiagnosticRoute
  AuthenticatedAdminHhcRoute: typeof AuthenticatedAdminHhcRoute
  AuthenticatedAdminLowStockRoute: typeof AuthenticatedAdminLowStockRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductHuntingRoute: typeof AuthenticatedAdminProductHuntingRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUserDataRoute: typeof AuthenticatedAdminUserDataRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVouchersRoute: typeof AuthenticatedAdminVouchersRoute
  AuthenticatedAdminWebsiteReviewsRoute: typeof AuthenticatedAdminWebsiteReviewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityLogsRoute: AuthenticatedAdminActivityLogsRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminDefectReportsRoute: AuthenticatedAdminDefectReportsRoute,
  AuthenticatedAdminDiagnosticRoute: AuthenticatedAdminDiagnosticRoute,
  AuthenticatedAdminHhcRoute: AuthenticatedAdminHhcRoute,
  AuthenticatedAdminLowStockRoute: AuthenticatedAdminLowStockRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductHuntingRoute: AuthenticatedAdminProductHuntingRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUserDataRoute: AuthenticatedAdminUserDataRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVouchersRoute: AuthenticatedAdminVouchersRoute,
  AuthenticatedAdminWebsiteReviewsRoute: AuthenticatedAdminWebsiteReviewsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentMethodsRoute: typeof AccountPaymentMethodsRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountVouchersRoute: typeof AccountVouchersRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentMethodsRoute: AccountPaymentMethodsRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountVouchersRoute: AccountVouchersRoute,
  AccountWishlistRoute: AccountWishlistRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmOrderRoute: ConfirmOrderRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportDefectiveRoute: ReportDefectiveRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
